version: '3.3'
services:
  tomcat:
    depends_on:
      - mongo
    image: magsenabbe/gigwa:2.2-RELEASE
    ports:
      - 8080:8080
    restart: always
    environment:
      MONGO_IP: 
      MONGO_PORT: 
    volumes:
      - type: volume
        source: gigwa
        target: /usr/local/tomcat/config

  mongo:
    image: mongo
    restart: always
    command: --slowms 60000 --storageEngine wiredTiger --wiredTigerCollectionBlockCompressor=zlib
    ports:
      - 59393:27017
    volumes:
      - type: volume
        source: mongo
        target: /data/db

volumes:
  gigwa:
  mongo: