version: '3.3'
services:
  tomcat:
    depends_on:
      - mongo
    image: guilhemsempere/gigwa:2.3-RELEASE
    ports:
      - 8080:8080
    restart: always
    environment:
      MONGO_IP: mongo.container.ip.address
      MONGO_PORT: 59393
      MONGO_INITDB_ROOT_USERNAME: yourMongoRootUser
      MONGO_INITDB_ROOT_PASSWORD: yourMongoRootPassword
    volumes:
      - type: volume
        source: gigwa
        target: /usr/local/tomcat/config

  mongo:
    image: mongo
    restart: always
    command: --slowms 60000 --storageEngine wiredTiger --wiredTigerCollectionBlockCompressor=zlib --directoryperdb
    ports:
      - 59393:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: yourMongoRootUser
      MONGO_INITDB_ROOT_PASSWORD: yourMongoRootPassword
    volumes:
      - type: volume
        source: mongo
        target: /data/db

volumes:
  gigwa:
  mongo: