name: Gigwa Build workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Run build script
      run: |
        wget https://raw.githubusercontent.com/SouthGreenPlatform/Gigwa2/master/misc/build.sh
        chmod +x build.sh
        ./build.sh -P prod
    - name: Create Release
      id: create_release
      run: |
        response=$(curl -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"tag_name": "2.6.2-RELEASE", "draft": false}' "https://api.github.com/repos/${{ github.repository }}/releases")
        echo "::set-output name=upload_url::$(echo "$response" | jq -r '.upload_url')"
      shell: bash
      env:
        RELEASE_API_RESPONSE: ${{ steps.create_release.outputs.response }}
    - name: Upload Release Asset
      run: |
        curl -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" --data-binary @"Gigwa2/target/Gigwa_V2.6.2-RELEASE_Webapp.zip" "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.release_id }}/assets?name=Gigwa_V2.6.2-RELEASE_Webapp.zip"
